### ISSUE TITLE
tsMuxeR version after git-7740bd5@Win10 64bit wrong detect mvc stream in mpls

### ISSUE THREAD

**Issue by abakum** [justdan96/tsMuxer#209]
c:\msys64\home\Konstantin.Abakumov>tsMuxeR.exe "d:\AV\2019\20190617 Море\film\20190617 Море 102455 Привал\BDMV\PLAYLIST\00000.mpls"
tsMuxeR version git-d817a09. github.com/justdan96/tsMuxer
Track ID:    4113
Stream type: H.264
Stream ID:   V_MPEG4/ISO/AVC
Stream info: Profile: High@4.2  Resolution: 1920:1080p  Frame rate: 25
Stream lang:

Track ID:    4352
Stream type: LPCM
Stream ID:   A_LPCM
Stream info: Bitrate: 1536Kbps  Sample Rate: 48KHz  Channels: 2  Bits per sample: 16bit
Stream lang:

Track ID:    4608
Stream type: PGS
Stream ID:   S_HDMV/PGS
Stream info: Presentation Graphic Stream #0 Resolution: 1920:1080 Frame rate: 25   3d-plane: undefined
Stream lang:

File #00000 name=d:\AV\2019\20190617 ђ_ђ_‘_ђз\film\20190617 ђ_ђ_‘_ђз 102455 ђ_‘_ђсђ_ђшђ>\BDMV\STREAM\SSIF\00000.ssif
Duration: 00:00:04.000
Base view: left-eye
start-time: 189000000
Marks: 00:00:00.000

**Comment by abakum** [comment]
c:\msys64\home\Konstantin.Abakumov>tsMuxeR12.exe "d:\AV\2019\20190617 Море\film\20190617 Море 102455 Привал\BDMV\PLAYLIST\00000.mpls"
Network Optix tsMuxeR.  Version 2.6.12. www.networkoptix.com
Track ID:    4114
Stream type: MVC
Stream ID:   V_MPEG4/ISO/MVC
Stream info: H.264/MVC Views: 2 Profile: High@4.2  Resolution: 1920:1080p  Frame rate: 25
Stream lang:
Track ID:    4113
Stream type: H.264
Stream ID:   V_MPEG4/ISO/AVC
Stream info: Profile: High@4.2  Resolution: 1920:1080p  Frame rate: 25
Stream lang:

Track ID:    4352
Stream type: LPCM
Stream ID:   A_LPCM
Stream info: Bitrate: 1536Kbps  Sample Rate: 48KHz  Channels: 2  Bits per sample: 16bit
Stream lang: rus

Track ID:    4608
Stream type: PGS
Stream ID:   S_HDMV/PGS
Stream info: Presentation Graphic Stream #0 Resolution: 1920:1080 Frame rate: 25   3d-plane: zero
Stream lang: rus

File #00000 name=d:\AV\2019\20190617 Њ®аҐ\film\20190617 Њ®аҐ 102455 ЏаЁў «\BDMV\STREAM\SSIF\00000.ssif
Duration: 00:00:04.000
Base view: left-eye
start-time: 189000000
Marks: 00:00:00.000

**Comment by abakum** [comment]
![image](https://user-images.githubusercontent.com/18271863/75344594-fddd1d80-58ab-11ea-8b46-b1b428813023.png)

**Comment by abakum** [comment]
![image](https://user-images.githubusercontent.com/18271863/75345325-91631e00-58ad-11ea-9674-18df0c1b932a.png)

**Comment by abakum** [comment]
Latest working version:  w64-nightly-2020-02-03--01-09-07.zip
tsMuxeR version git-7740bd5. github.com/justdan96/tsMuxer
Track ID:    4114
Stream type: MVC
Stream ID:   V_MPEG4/ISO/MVC
Stream info: H.264/MVC Views: 2 Profile: High@4.2  Resolution: 1920:1080p  Frame rate: 25
Stream lang:
Track ID:    4113
Stream type: H.264
Stream ID:   V_MPEG4/ISO/AVC
Stream info: Profile: High@4.2  Resolution: 1920:1080p  Frame rate: 25
Stream lang:

**Comment by jcdr428** [comment]
@abakum unfortenately, I can't reproduce: everything is working fine on W64.
Tried with 3D samples from https://kodi.wiki/view/Samples#3D_Test_Clips:

```
tsMuxeR version git-d817a09. github.com/justdan96/tsMuxer
Track ID:    4114
Stream type: MVC
Stream ID:   V_MPEG4/ISO/MVC
Stream info: H.264/MVC Views: 2 Profile: High@4.1  Resolution: 1920:1080p  Frame rate: 23.976  3d-pg-planes: 32
Stream lang: 

Track ID:    4113
Stream type: H.264
Stream ID:   V_MPEG4/ISO/AVC
Stream info: Profile: High@4.1  Resolution: 1920:1080p  Frame rate: 23.976
Stream lang: 

Track ID:    4352
Stream type: AC3
Stream ID:   A_AC3
Stream info: Bitrate: 640Kbps Sample Rate: 48KHz Channels: 5.1
Stream lang: chi

Track ID:    4608
Stream type: PGS
Stream ID:   S_HDMV/PGS
Stream info: Presentation Graphic Stream #0 Resolution: 1920:1080 Frame rate: 23.976
Stream lang: eng

Duration: 00:01:14.824
```
The merge after 7740bd5 is the one line merge b8d9788 , which changes the GUI but not the CLI. So the change affecting the behavior of MVC would come from 2f20f31 ?

**Comment by abakum** [comment]
Eureka!
After I removed all non-Latin letters from the path to mpls it worked!
![image](https://user-images.githubusercontent.com/18271863/75390853-170cbb00-58fa-11ea-8104-f4804fd41afc.png)

**Comment by abakum** [comment]
Add letter я and again
![image](https://user-images.githubusercontent.com/18271863/75391129-94d0c680-58fa-11ea-87ba-2fcc09bf1f95.png)

**Comment by justdan96** [comment]
@xavery FYI

**Comment by xavery** [comment]
This should be fixed now. Keep in mind that the console output will be borked due to the simple fact that the process' standard output is used by the GUI in the stream detection phase and thus must be encoded in UTF-8. The characters will not show up properly in the Windows console unless you switch it to UTF-8 manually.
Standard console :
![image](https://user-images.githubusercontent.com/127875/75471101-060f8880-5992-11ea-9f33-e0772eba3182.png)

With `chcp 65001` :
![image](https://user-images.githubusercontent.com/127875/75471126-0f005a00-5992-11ea-96ad-4d98ff67ebea.png)

**Comment by justdan96** [comment]
Is there an opportunity to update the documentation here as well, to reduce confusion?

**Comment by xavery** [comment]
@justdan96 Updated in e9d438bbbca90438916abfca90a4a67ff8cbf956.

**Comment by abakum** [comment]
Thanks @xavery but bug not fixed :(
Track ID:    4114
Track ID:    4113
Track ID:    4352
...
![image](https://user-images.githubusercontent.com/18271863/75474003-36aded00-59a7-11ea-8303-24d764a07a80.png)
After add я to path tsmuxer stopped deteсt MVC tracks:
Track ID:    4114
Stream type: MVC
Stream ID:   V_MPEG4/ISO/MVC
Stream info: H.264/MVC Views: 2 Profile: High@4.1  Resolution: 1920:1080p  Frame rate: 23.976  3d-pg-planes: 32
Stream lang:
Only:
Track ID:    4113
Track ID:    4352
...
![image](https://user-images.githubusercontent.com/18271863/75474165-8db3c200-59a7-11ea-9bd1-447049e6fcd0.png)

**Comment by xavery** [comment]
Fascinating. I'll need to look into this once more, then.

**Comment by abakum** [comment]
But non-Latin char in GUI fixed!
![image](https://user-images.githubusercontent.com/18271863/75477917-1170ad00-59ae-11ea-95c1-b8cc19ffa627.png)

**Comment by xavery** [comment]
@abakum Please try again now - I've tested with the same example, and the results are the same regardless of whether the path contains `я` or not. The issue was with the Windows POSIX compatibility APIs reporting that the file doesn't exist because the character encoding was treated as ACP behind the scenes.

**Comment by abakum** [comment]
Coooool! Thanks @xavery 
![image](https://user-images.githubusercontent.com/18271863/75512321-119a9800-5a02-11ea-99ce-f4ba6eaa7b3e.png)
